version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo check if AWS CLI installed...
      - aws --version
      - echo check if Python installed...
      - python3 --version
      - echo check if PIP python package manager installed...
      - pip3 --version
      - echo installing CFN-LINT..
      - pip3 install cfn-lint
      - echo check CFN-LINT installed...
      - cfn-lint --version
  build:
    commands:
      - echo Validating the cfn template
      - cfn-lint 1-ec2-user-data.yaml
      - echo cfn template Build started on 'date'
      - aws cloudformation package --template-file 1-ec2-user-data.yaml --s3-bucket dee-deployed-artifacts-bucket --output-template-file outputTemplate.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - outputTemplate.yaml # this will be zipped in our build artifact
    - 1-ec2-user-data.yaml
    